### ISSUE TITLE
RealityKit when using arView.prepareForRecording() SessionDelegate can not work

### ISSUE THREAD

**Issue by frank-1992** [gorastudio-ceo/SCNRecorder#42]
ARSessionDelegate can't run, when I use self.arView.prepareForRecording()
do you know why?

**Comment by frank-1992** [comment]
I know why, please see this cod
<img width="381" alt="企业微信截图_b7d6be16-3e35-49c2-b98a-043b0cbd770f" src="https://user-images.githubusercontent.com/103110407/168992428-26096900-32d5-4071-b4ce-526f8ba7e5ae.png">
e

**Comment by v-grigoriev** [comment]
Hi @frank-1992, yeah, I wanted to reply the same.
Since the integration with reality kit is done outside the library feel free to modify it.
And for the same reason I did solve this for ARSCNView, but not for ARView.

sceneRecorder only needs to be notified about audio data.
So if you want to record the default ARSession audio together with video frames.
somewhere where you implements the ARSessionDelegate
do the following

```
  func session(_ session: ARSession, didOutputAudioSampleBuffer audioSampleBuffer: CMSampleBuffer) {
    realityView.sceneRecorder?.session(session, didOutputAudioSampleBuffer: audioSampleBuffer)
  }
```

**Comment by frank-1992** [comment]
> Hi @frank-1992, yeah, I wanted to reply the same. Since the integration with reality kit is done outside the library feel free to modify it. And for the same reason I did solve this for ARSCNView, but not for ARView.
> 
> sceneRecorder only needs to be notified about audio data. So if you want to record the default ARSession audio together with video frames. somewhere where you implements the ARSessionDelegate do the following
> 
> ```
>   func session(_ session: ARSession, didOutputAudioSampleBuffer audioSampleBuffer: CMSampleBuffer) {
>     realityView.sceneRecorder?.session(session, didOutputAudioSampleBuffer: audioSampleBuffer)
>   }
> ```

Thank you, very nice job
